In [4]:
import pandas as pd

In [9]:
from sklearn.datasets import load_diabetes

diabetes = load_diabetes()

X=pd.DataFrame(diabetes["data"], columns=diabetes["feature_names"])
y = diabetes["target"]

In [10]:
X

          age       sex       bmi  ...        s4        s5        s6
0    0.038076  0.050680  0.061696  ... -0.002592  0.019907 -0.017646
1   -0.001882 -0.044642 -0.051474  ... -0.039493 -0.068332 -0.092204
2    0.085299  0.050680  0.044451  ... -0.002592  0.002861 -0.025930
3   -0.089063 -0.044642 -0.011595  ...  0.034309  0.022688 -0.009362
4    0.005383 -0.044642 -0.036385  ... -0.002592 -0.031988 -0.046641
..        ...       ...       ...  ...       ...       ...       ...
437  0.041708  0.050680  0.019662  ... -0.002592  0.031193  0.007207
438 -0.005515  0.050680 -0.015906  ...  0.034309 -0.018114  0.044485
439  0.041708  0.050680 -0.015906  ... -0.011080 -0.046883  0.015491
440 -0.045472 -0.044642  0.039062  ...  0.026560  0.044529 -0.025930
441 -0.045472 -0.044642 -0.073030  ... -0.039493 -0.004222  0.003064

[442 rows x 10 columns]

In [11]:
y

array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
       128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
       150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
       200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
        42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
        83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
       104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
       173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
       107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
        60., 174., 259., 178., 128.,  96., 126., 288.,  88., 292.,  71.,
       197., 186.,  25.,  84.,  96., 195.,  53., 217., 172., 131., 214.,
        59.,  70., 220., 268., 152.,  47.,  74., 295., 101., 151., 127.,
       237., 225.,  81., 151., 107.,  64., 138., 185., 265., 101., 137.,
       143., 141.,  79., 292., 178.,  91., 116.,  86., 122.,  72., 129.,
       142.,  90., 158.,  39., 196., 222., 277.,  99., 196., 202., 155.,
        77., 191.,  70.,  73.,  49.,  65., 263., 248., 296., 214., 185.,
        78.,  93., 252., 150.,  77., 208.,  77., 108., 160.,  53., 220.,
       154., 259.,  90., 246., 124.,  67.,  72., 257., 262., 275., 177.,
        71.,  47., 187., 125.,  78.,  51., 258., 215., 303., 243.,  91.,
       150., 310., 153., 346.,  63.,  89.,  50.,  39., 103., 308., 116.,
       145.,  74.,  45., 115., 264.,  87., 202., 127., 182., 241.,  66.,
        94., 283.,  64., 102., 200., 265.,  94., 230., 181., 156., 233.,
        60., 219.,  80.,  68., 332., 248.,  84., 200.,  55.,  85.,  89.,
        31., 129.,  83., 275.,  65., 198., 236., 253., 124.,  44., 172.,
       114., 142., 109., 180., 144., 163., 147.,  97., 220., 190., 109.,
       191., 122., 230., 242., 248., 249., 192., 131., 237.,  78., 135.,
       244., 199., 270., 164.,  72.,  96., 306.,  91., 214.,  95., 216.,
       263., 178., 113., 200., 139., 139.,  88., 148.,  88., 243.,  71.,
        77., 109., 272.,  60.,  54., 221.,  90., 311., 281., 182., 321.,
        58., 262., 206., 233., 242., 123., 167.,  63., 197.,  71., 168.,
       140., 217., 121., 235., 245.,  40.,  52., 104., 132.,  88.,  69.,
       219.,  72., 201., 110.,  51., 277.,  63., 118.,  69., 273., 258.,
        43., 198., 242., 232., 175.,  93., 168., 275., 293., 281.,  72.,
       140., 189., 181., 209., 136., 261., 113., 131., 174., 257.,  55.,
        84.,  42., 146., 212., 233.,  91., 111., 152., 120.,  67., 310.,
        94., 183.,  66., 173.,  72.,  49.,  64.,  48., 178., 104., 132.,
       220.,  57.])

In [12]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.25, random_state=42)

In [13]:
X_train

          age       sex       bmi  ...        s4        s5        s6
16  -0.005515 -0.044642  0.042296  ... -0.039493  0.052277  0.027917
408  0.063504 -0.044642 -0.050396  ...  0.023608  0.058038  0.040343
432  0.009016 -0.044642  0.055229  ...  0.023239  0.055686  0.106617
316  0.016281  0.050680  0.014272  ...  0.034309  0.074966  0.040343
3   -0.089063 -0.044642 -0.011595  ...  0.034309  0.022688 -0.009362
..        ...       ...       ...  ...       ...       ...       ...
106 -0.096328 -0.044642 -0.076264  ... -0.039493 -0.059471 -0.083920
270  0.005383  0.050680  0.030440  ... -0.039493  0.008641  0.015491
348  0.030811 -0.044642 -0.020218  ... -0.039493 -0.010903 -0.001078
435 -0.012780 -0.044642 -0.023451  ... -0.002592 -0.038460 -0.038357
102 -0.092695 -0.044642  0.028284  ... -0.039493 -0.005142 -0.001078

[331 rows x 10 columns]

In [14]:
X_test

          age       sex       bmi  ...        s4        s5        s6
287  0.045341 -0.044642 -0.006206  ...  0.034309  0.032432 -0.005220
211  0.092564 -0.044642  0.036907  ... -0.039493 -0.022517 -0.021788
72   0.063504  0.050680 -0.004050  ... -0.002592  0.084492 -0.017646
321  0.096197 -0.044642  0.051996  ...  0.141322  0.098648  0.061054
73   0.012648  0.050680 -0.020218  ...  0.034309 -0.005142 -0.009362
..        ...       ...       ...  ...       ...       ...       ...
45   0.027178  0.050680 -0.035307  ... -0.002592 -0.014960 -0.050783
153  0.041708  0.050680 -0.043929  ... -0.002592 -0.034522  0.011349
239  0.023546 -0.044642  0.019662  ... -0.002592  0.066051  0.048628
380  0.016281 -0.044642  0.026128  ... -0.033958 -0.051404 -0.025930
278  0.067136  0.050680 -0.036385  ...  0.034309  0.001148  0.032059

[111 rows x 10 columns]

In [15]:
y_train

array([166., 189., 173., 220., 206.,  97.,  60.,  61., 242., 121., 128.,
       104., 265., 132., 283., 174., 129., 257., 137.,  63.,  93., 232.,
       208., 261., 179., 258., 262.,  51., 237.,  71., 139., 268.,  69.,
       317., 249., 154., 192., 116.,  81., 122., 259., 191., 292.,  55.,
       107., 210.,  91., 253.,  85., 252.,  59.,  78., 200.,  78., 245.,
       175.,  42., 127.,  53.,  94., 104., 199., 265., 281., 248., 257.,
       215., 303., 170.,  59., 277., 209., 138., 198., 124.,  96., 288.,
       225., 265., 101.,  55., 198.,  51., 252.,  64., 220., 131., 212.,
       142., 103., 155., 121.,  86., 111.,  65., 131.,  51., 128., 141.,
        48., 109., 178.,  88.,  84., 216., 150.,  60.,  96., 190.,  74.,
       279., 182., 160., 245., 276., 174., 180., 150., 196., 138.,  97.,
       246., 321., 308., 109.,  69., 182., 258., 161., 178., 214.,  45.,
       150., 160.,  55., 197., 185., 268., 310., 123.,  68.,  72., 185.,
       144., 147., 168., 178., 246., 151., 127.,  83., 332., 152., 109.,
        90.,  66., 214.,  85., 129.,  89., 259., 229., 200.,  77.,  54.,
        31., 109., 206., 144., 118.,  83., 242., 259.,  72., 163., 181.,
       141.,  71., 137., 195., 179., 102., 131.,  47., 235.,  77., 198.,
        93., 162., 225., 275., 183., 306.,  81.,  55., 146., 196., 230.,
       310.,  40., 135., 346.,  43., 128.,  77., 235.,  49.,  74.,  92.,
        84., 263., 144., 142., 341., 115., 158., 273.,  85.,  88., 220.,
        39.,  80., 172., 217., 336.,  52., 272., 115., 110., 131.,  71.,
       275., 118.,  25., 100., 281., 221., 248., 200., 132.,  91.,  67.,
       202.,  73.,  85., 275., 243.,  66., 293., 236., 243.,  87.,  39.,
       217.,  92., 296., 292., 142.,  50.,  53., 104.,  75., 120., 142.,
       143.,  99.,  65., 116., 233., 164.,  95.,  59., 139., 145., 177.,
       185.,  97.,  42., 201., 241.,  70.,  78.,  49., 103.,  44., 111.,
       191.,  47., 182.,  58., 155., 151.,  79., 104., 143., 152., 170.,
        75., 200., 124.,  91.,  49., 163.,  53., 283., 178., 219., 200.,
       113., 113.,  63., 114., 126., 274.,  88., 311.,  83.,  71., 134.,
       244.,  65., 173.,  57.,  68., 141., 270., 134., 202., 148.,  64.,
       302.])

In [16]:
y_test

array([219.,  70., 202., 230., 111.,  84., 242., 272.,  94.,  96.,  94.,
       252.,  99., 297., 135.,  67., 295., 264., 170., 275., 310.,  64.,
       128., 232., 129., 118., 263.,  77.,  48., 107., 140., 113.,  90.,
       164., 180., 233.,  42.,  84., 172.,  63.,  48., 108., 156., 168.,
        90.,  52., 200.,  87.,  90., 258., 136., 158.,  69.,  72., 171.,
        95.,  72., 151., 168.,  60., 122.,  52., 187., 102., 214., 248.,
       181., 110., 140., 202., 101., 222., 281.,  61.,  89.,  91., 186.,
       220., 237., 233.,  68., 190.,  96.,  72., 153.,  98.,  37.,  63.,
       184., 144., 150., 280., 125.,  59.,  65., 281., 277., 167.,  90.,
        72., 178.,  88., 270., 101., 197.,  97.,  53.,  71., 262.,  52.,
       102.])

In [28]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import GridSearchCV
import warnings
warnings.filterwarnings("ignore")

param = {
    'criterion': ['squared_error', 'absolute_error', 'poisson'],
    'splitter': ['best', 'random'],
    'max_depth': [1, 2, 3, 4, 5, 10, 15, None],
    'max_features': [1.0, 'sqrt', 'log2']
}

regressor = DecisionTreeRegressor()
grid = GridSearchCV(regressor, param_grid=param, cv=5, scoring="r2")
grid.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=DecisionTreeRegressor(),
             param_grid={'criterion': ['squared_error', 'absolute_error',
                                       'poisson'],
                         'max_depth': [1, 2, 3, 4, 5, 10, 15, None],
                         'max_features': [1.0, 'sqrt', 'log2'],
                         'splitter': ['best', 'random']},
             scoring='r2')

In [29]:
from sklearn.metrics import r2_score

y_pred = grid.predict(X_test)
print(r2_score(y_test, y_pred))

0.35877796827013275